ACCELERATION_DIVIDER = 20
DECELERATION_LIMIT = 0.5
HEIGHT_CHANGE_DIVIDER = 20
MINIMAL_STEP = 0.2

# Fuel consumption calculating
ACCELERATION_MODIFIER_DIVIDER = 1
DECELERATION_MODIFIER_DIVIDER = 10
PRESSURE_DIVIDER_MODIFIER = 3
